aclfile /usr/local/etc/redis/users.acl
maxmemory 256mb
maxmemory-policy noeviction
save ""
appendonly yes
appendfsync everysec
tls-port 6380
tls-cert-file /usr/local/etc/redis/tls/redis.crt
tls-key-file /usr/local/etc/redis/tls/redis.key
tls-ca-cert-file /usr/local/etc/redis/tls/ca.crt
tls-auth-clients no
